# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    branches: [ "main" ]
    types: [update_blog]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18.12.1
    - run: touch src/.env
    - run: echo "API_KEY=${{ secrets.MICROCMS_BLOG_API_KEY }}" >> src/.env
    - name: yarn install
      run: |
           npm install
           npm run build
    - name: deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:ssr
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - run: rm src/pages/preview.jsx
    - run: npm install
    - run: npm run export
    - name: deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:ssg
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
